Update batch5_errorcheck

diff --git a/jenkins/batch5_errorcheck b/jenkins/batch5_errorcheck
--- a/jenkins/batch5_errorcheck
+++ b/jenkins/batch5_errorcheck
@@ -1,39 +1,44 @@
 boolean isBuild=false
 pipeline{
-    agent any 
+    agent any
 
-      stages{
+    stages{
         stage('A'){
-          steps{
-              catchError( buildStatus='SUCCESS', stageStatus='FAILURE')
-              { 
-              echo 'Stage A is running'
-              isBuild = true
-             
-        }
-        }
-        } 
+            steps{
+            
+                catchError(buildResult:'SUCCESS', stageResult:'FAILURE'){
+                    echo 'Stage A is Running'
+                    script{
+						//sh 'exit 1'
+                        echo 'Stage A successful'
+						isBuild = true
+					}
+				}
+			}
+        }
 
-        stage('B'){
-            when {
-                expression {
-                    isBuild == true
-                }
-            }
-            steps{
-                echo 'Stage B is running'
-            }
-        } 
+        stage('B'){
+            when {
+                expression {
+                    isBuild == true
+                }
+            }
+            steps{
+                echo 'Stage B is running'
+                echo 'Congrats, stage A completed'
+            }
+        }
 
-        stage('C'){
-            when {
-                expression {
-                    isBuild == false
-                }
-            }
-            steps{
-                echo 'Stage C is running'
-            }
-        }
-    }
+        stage('C'){
+            when {
+                expression {
+                    isBuild == false
+                }
+            }
+            steps{
+                echo 'Stage C is running'
+                echo 'Sorry, Stage A Failed.'
+            }
+        }
+    }
 }
